# Configuration file for AppVeyor continuous integration on Windows
# adapted from MDTraj project (http://mdtraj.org/)

os: Windows Server 2012

install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:\get-pip.py')
  - C:\Python27\python.exe c:\get-pip.py
  - C:\Python27\Scripts\pip.exe install pyyaml
  - C:\Python27\Scripts\pip.exe install pycosat
  - C:\Python27\Scripts\pip.exe install conda
  - C:\Python27\Scripts\conda.exe init
  - C:\Python27\Scripts\conda.exe create -n build_env --yes --quiet python=3.3 setuptools pip numpy six cython
  - dir C:\Python27\envs\build_env
  - dir C:\Python27\envs\build_env\Scripts
  - C:\Python27\envs\build_env\Scripts\pip install wheel
  - cinst 7zip
  - ps: (new-object net.webclient).DownloadFile('https://github.com/scikit-image/scikit-image/archive/v0.10.0.zip', 'C:\v0.10.0.zip')
  - 7z x C:\v0.10.0.zip -oC:\tmp\skimage

build_script:
  - cd C:\tmp\skimage\scikit-image-0.10.0
  - dir
  - C:\Python27\envs\build_env\python.exe setup.py bdist_wheel
  - dir dist

test_script:
  - SET PATH=%PATH%;C:\Python27\envs\build_env\Scripts
  - C:\Python27\envs\build_env\python.exe setup.py install 
  - C:\Python27\envs\build_env\Scripts\nosetests -v
